import AuthProvider from './AuthProvider';
import Signout from './Sigout';
import './globals.css';

export const metadata = {
  title: 'origin-health',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <div className='fixed bottom-4 right-4 text-2xl bg-white text-black p-4 rounded-lg'>
          <Signout />
        </div>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
